Page news
STUD-IT-team/bmstu-stud-web-frontend-old pull request #15
Opened 2024-07-04 10:33 UTC by just-rudy

2024-07-06 17:41 UTC, SergTyapkin requested changes

2024-07-06 17:41 UTC, SergTyapkin commented on res/images/big-new-two.png
Когда ты заливаешь любой файл и вообще любые изменения - они остаются в истории коммитов, и вырезать их оттуда потом очень костыльно и сложно. 
Потому когда ты заливаешь картинку и потом где-то удаляешь, то люди, которые потом скачивают проект и историю коммитов, скачивают и эту картинку, потому что в одном коммите есть инфа, что она добавилась, а в другом, что эти байты были удалены. Но размер оно все занимает тот же

2024-07-06 17:41 UTC, SergTyapkin commented on src/components/OneBigNew.vue
> +    transition filter 0.3s
`user-select: none`

2024-07-06 17:41 UTC, SergTyapkin commented on src/components/OneBigNew.vue
> +    <div class="title">{{ title }}</div>
лучше `<header>`

2024-07-06 17:41 UTC, SergTyapkin commented on src/components/OneBigNew.vue
> +      &emsp; Читать подробнее
Сейчас бы `padding-left` делать через неразрывный пробел

2024-07-06 17:41 UTC, SergTyapkin commented on src/components/OneBigNew.vue
> +    width 396px
Почему не `100%`?

2024-07-06 17:41 UTC, SergTyapkin commented on src/components/OneBigNew.vue
> +    border-radius 20px
Вынеси `20px` в переменную. Она используется в разных блоках и должна быть везде одинаковая

2024-07-06 17:41 UTC, SergTyapkin commented on src/components/OneBigNew.vue
> +  width 400px
![image](https://github.com/STUD-IT-team/bmstu-stud-web-frontend/assets/18362352/a82f3216-bbd9-4ad8-a1a8-e649df5031f7)

На узких экранах картинки начинают переноситься.
Можно было сделать, чтобы они чуть уменьшались. Для этого надо `min-width` и `max-width` вместе с `width: max-content`.

Либо сделать горизонтальный скролл, тогда 400px условно можно оставить

2024-07-06 17:41 UTC, SergTyapkin commented on src/components/OneBigNew.vue
> +  height 315px
Зачем ограничивать высоту? Пусть она сама складывается из внутренних элементов

2024-07-06 17:41 UTC, SergTyapkin commented on src/components/OneBigNew.vue
> +    <div class="description">{{ description }}</div>
Если description должен быть именно поверх картинки, засунь оба этих элемента в `<div>` контейнер с `position: relative`. 

Не надо позиционировать `.description` внутри всего внешнего элемента

2024-07-06 17:41 UTC, SergTyapkin commented on src/components/OneBigNew.vue
> +    display none
Спрячь его через `opacity: 0`, тогда будет работать `transition`

2024-07-06 17:41 UTC, SergTyapkin commented on src/components/OneBigNew.vue
> +    openRedirectLink() {
Оно же нигде не используется

2024-07-06 17:41 UTC, SergTyapkin commented on src/utils/apiModels.js
> +    item: StudNumber,
Если сущность StudNumber не используется нигде отдельно, то можно прописать всё в одном объекте.

[Дока тут](https://github.com/SergTyapkin/js-models-validator?tab=readme-ov-file#docs-for-models)

2024-07-06 17:41 UTC, SergTyapkin commented on src/views/PageNews.vue
> +      const sliderElement = document.getElementById('slider');
Сделай через $ref

2024-07-06 17:41 UTC, SergTyapkin commented on src/views/PageNews.vue
> +      });
Ну тут все расписывал в ТГ

2024-07-06 17:41 UTC, SergTyapkin commented on src/views/PageNews.vue
> +          <a href="#slider" @click.prevent="scrollToSlider">
Ну я бы прям сюда `window.scroll($refs.slider)` написал

2024-07-06 17:41 UTC, SergTyapkin commented on src/views/PageNews.vue
> +    width 100vw
Лучше 100%. Внешний элемент и так 100vw

2024-07-06 17:41 UTC, SergTyapkin commented on src/views/PageNews.vue
> +    flex-direction row
Он и так по умолчанию row

2024-07-06 17:41 UTC, SergTyapkin commented on src/views/PageNews.vue
> +      margin 15px
Тут лучше margin только горизонтальный, внутри этого элемента. А margin вертикальный выеси в контейнер для внутренних элементов, потому что он подразумевает логику позиционирования этого большого листинга относительно всех остальных элементов на странице

2024-07-06 17:41 UTC, SergTyapkin commented on src/views/PageNews.vue
> +    padding-left 15rem
Почему именно в rem'ах. Чем это здесь оправдано?

2024-07-06 17:41 UTC, SergTyapkin commented on src/views/PageNews.vue
> +    list-style-type none
`list-style: none`

2024-07-06 17:41 UTC, SergTyapkin commented on src/views/PageNews.vue
> +          top 67%
Позиционируй от нижней границы, а не от верхней. 
Она в правом нижнем углу, и задавать нужно расстояние до правой и нижней границы

2024-07-06 17:41 UTC, SergTyapkin commented on src/views/PageNews.vue
> +          user-select: none
убери `:`

2024-07-06 17:41 UTC, SergTyapkin commented on src/views/PageNews.vue
> +          top 29%
Это нужно спозиционировать по центру по вертикали, и на расстоянии от левой границы.

Потому 
`top 50%`
`transform translateY(-50%)`

2024-07-06 17:41 UTC, SergTyapkin commented on src/views/PageNews.vue
> +        top 10px
Лишнее

2024-07-06 17:41 UTC, SergTyapkin commented on src/views/PageNews.vue
> +      margin-bottom 0
Зачем?

2024-07-06 17:41 UTC, SergTyapkin commented on src/utils/apiModels.js
> +    item: StudBigNew,
Тут то же самое

2024-07-06 17:41 UTC, SergTyapkin commented on src/components/OneBigNew.vue
> +    transition background 0.3s, color 0.3s
0.3 обычно бывает много. Я во всех проектах ставлю 0.2, кажется, что всё начинает работать быстрее и повышается отзывчивость

2024-07-06 17:41 UTC, SergTyapkin commented on src/components/OneBigNew.vue
> +    border-style solid
Зачем разделила

2024-07-06 17:41 UTC, SergTyapkin commented on src/components/OneBigNew.vue
> +    margin 8px
Из-за ограничения на высоту всего блока, здесь margin не работает, как ожидается
![image](https://github.com/STUD-IT-team/bmstu-stud-web-frontend/assets/18362352/bdbf5f04-9176-4818-bfc2-c205a5d1ec0a)

2024-07-06 17:41 UTC, SergTyapkin commented on src/components/OneBigNew.vue
> +    align-self right
Это работает только в специфических случаях для элементов внутри flex-контейнеров. Не тут точно

2024-07-06 17:41 UTC, SergTyapkin commented on src/components/OneBigNew.vue
> +  display flex
Зачем здесь вообще flex? Лучше без него

2024-07-06 17:41 UTC, SergTyapkin commented on src/views/PageNews.vue
> +      margin-left 95vw
`margin-left auto`

2024-07-06 17:41 UTC, SergTyapkin commented on src/views/PageNews.vue
> +      margin-left 95vw
Ну и справа тогда отступ можно нормально регулировать будет через `margin-right`

2024-07-08 06:59 UTC, just-rudy commented on res/images/big-new-two.png
Есть совет, как тогда делать?
Не коммитить картинки? или как-то следить за их удалением и предупреждать о них людей?)

2024-07-08 07:08 UTC, just-rudy commented on src/components/OneBigNew.vue
> +    <div class="title">{{ title }}</div>
вместо template?

2024-07-08 07:21 UTC, just-rudy commented on src/components/OneBigNew.vue
> +  width 400px
Вот я пыталась сделать горизонтальный скролл, но, видимо, я не понимаю, как его сделать
На блоке, в котором у меня большие новости на главной странице, стоит overflow-x scroll, но как-то они не начинают прокручиваться

2024-07-08 07:26 UTC, just-rudy commented on src/components/OneBigNew.vue
> +    margin 8px
Ограничен блок в высоту, чтобы его не размывало при сужении страницы

Как ты сделал так, что картинка в кнопке съехала?

2024-07-09 08:34 UTC, just-rudy commented on src/views/PageNews.vue
> +          top 29%
не согласна, я по фигме располагала
там она не по центру, насколько я вижу
![image](https://github.com/STUD-IT-team/bmstu-stud-web-frontend/assets/137426606/a44dd47c-27e9-48e0-aae9-4ae41391e51b)

2024-07-09 08:39 UTC, just-rudy commented on src/views/PageNews.vue
> +      margin-left 95vw
не-а
пыталась

![image](https://github.com/STUD-IT-team/bmstu-stud-web-frontend/assets/137426606/3ce370b0-8628-412b-838a-b328074ddb1c)

2024-07-16 07:56 UTC, merged